### ISSUE TITLE
Unable to do XCode Build with XCode Version 15.2 , 15.4 & 16.1 

### ISSUE THREAD

**Issue by ashraf-quantgen-dev** [rodgomesc/vision-camera-face-detector#56]
Pod Install succeeds , Worklets and Vision Camera Works too ...
But Doesn't compiles when added vision-camera-face-detector 

The Error is as : 

error export CLANG_WARN_DOCUMENTATION_COMMENTS\=YES
error export CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER\=NO
error export GCC_WARN_UNDECLARED_SELECTOR\=YES
error export VALIDATE_PRODUCT\=NO
error export GCC_WARN_PEDANTIC\=YES
error cannot find type 'FrameProcessorPluginBase' in scope
error \=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Index.noindex/DataStore @/Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -Wno-nullability-completeness -std\=c++20 -include /Users/ashrafkhan/FitWell-NishantTeam-main/ios/Pods/Target\ Support\ Files/ReactCodegen/ReactCodegen-prefix.pch -MMD -MT dependencies -MF /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnasyncstorage-generated.d --serialize-diagnostics /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnasyncstorage-generated.dia -c /Users/ashrafkhan/FitWell-NishantTeam-main/ios/build/generated/ios/rnasyncstorage/rnasyncstorage-generated.mm -o /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnasyncstorage-generated.o -index-unit-output-path /Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnasyncstorage-generated.o
error \=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Index.noindex/DataStore @/Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -Wno-nullability-completeness -std\=c++20 -include /Users/ashrafkhan/FitWell-NishantTeam-main/ios/Pods/Target\ Support\ Files/ReactCodegen/ReactCodegen-prefix.pch -MMD -MT dependencies -MF /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/RCTModulesConformingToProtocolsProvider.d --serialize-diagnostics /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/RCTModulesConformingToProtocolsProvider.dia -c /Users/ashrafkhan/FitWell-NishantTeam-main/ios/build/generated/ios/RCTModulesConformingToProtocolsProvider.mm -o /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/RCTModulesConformingToProtocolsProvider.o -index-unit-output-path /Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/RCTModulesConformingToProtocolsProvider.o
error \=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Index.noindex/DataStore @/Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -Wno-nullability-completeness -std\=c++20 -include /Users/ashrafkhan/FitWell-NishantTeam-main/ios/Pods/Target\ Support\ Files/ReactCodegen/ReactCodegen-prefix.pch -MMD -MT dependencies -MF /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontextJSI-generated.d --serialize-diagnostics /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontextJSI-generated.dia -c /Users/ashrafkhan/FitWell-NishantTeam-main/ios/build/generated/ios/safeareacontextJSI-generated.cpp -o /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontextJSI-generated.o -index-unit-output-path /Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontextJSI-generated.o
error \=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Index.noindex/DataStore @/Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -Wno-nullability-completeness -std\=c++20 -include /Users/ashrafkhan/FitWell-NishantTeam-main/ios/Pods/Target\ Support\ Files/ReactCodegen/ReactCodegen-prefix.pch -MMD -MT dependencies -MF /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontext-generated.d --serialize-diagnostics /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontext-generated.dia -c /Users/ashrafkhan/FitWell-NishantTeam-main/ios/build/generated/ios/safeareacontext/safeareacontext-generated.mm -o /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontext-generated.o -index-unit-output-path /Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/safeareacontext-generated.o
error \=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Index.noindex/DataStore @/Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -Wno-nullability-completeness -std\=c++20 -include /Users/ashrafkhan/FitWell-NishantTeam-main/ios/Pods/Target\ Support\ Files/ReactCodegen/ReactCodegen-prefix.pch -MMD -MT dependencies -MF /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvgJSI-generated.d --serialize-diagnostics /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvgJSI-generated.dia -c /Users/ashrafkhan/FitWell-NishantTeam-main/ios/build/generated/ios/rnsvgJSI-generated.cpp -o /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvgJSI-generated.o -index-unit-output-path /Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvgJSI-generated.o
error \=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Index.noindex/DataStore @/Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -Wno-nullability-completeness -std\=c++20 -include /Users/ashrafkhan/FitWell-NishantTeam-main/ios/Pods/Target\ Support\ Files/ReactCodegen/ReactCodegen-prefix.pch -MMD -MT dependencies -MF /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvg-generated.d --serialize-diagnostics /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvg-generated.dia -c /Users/ashrafkhan/FitWell-NishantTeam-main/ios/build/generated/ios/rnsvg/rnsvg-generated.mm -o /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvg-generated.o -index-unit-output-path /Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnsvg-generated.o
error \=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Index.noindex/DataStore @/Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -Wno-nullability-completeness -std\=c++20 -include /Users/ashrafkhan/FitWell-NishantTeam-main/ios/Pods/Target\ Support\ Files/ReactCodegen/ReactCodegen-prefix.pch -MMD -MT dependencies -MF /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnscreensJSI-generated.d --serialize-diagnostics /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnscreensJSI-generated.dia -c /Users/ashrafkhan/FitWell-NishantTeam-main/ios/build/generated/ios/rnscreensJSI-generated.cpp -o /Users/ashrafkhan/Library/Developer/Xcode/DerivedData/fwtmobapp-fbeyonmthpauekfuhguyxlswjsqa/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnscreensJSI-generated.o -index-unit-output-path /Pods.build/Debug-iphoneos/ReactCodegen.build/Objects-normal/arm64/rnscreensJSI-generated.o
error Failed to build ios project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'fwtmobapp.xcworkspace'.

**Comment by euroboy** [comment]
@ashraf-quantgen-dev Hi, did you fix these building errors?
