### ISSUE TITLE
Face detector fails build on android running RN 0.73.6

### ISSUE THREAD

**Issue by DanDance** [rodgomesc/vision-camera-face-detector#55]
I found out that the build started to fail after adding react-native-reanimated to the project. Tried different versions of this package. Faced this issue on my main work project, reproduced on new RN 0.73.6 project. This issue is not new and it completely blocks us from using this module.

Any help is really appreciated, thank you!

Dependecies:

> "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-reanimated": "2.17.0",
    "react-native-vision-camera": "^4.4.2",
    "react-native-worklets-core": "^1.3.3",
    "vision-camera-face-detector": "^0.1.8"

babel.config.js:

> module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    ['react-native-worklets-core/plugin'],
  ],
};

Error:

> RnPlayground/node_modules/vision-camera-face-detector/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPluginPackage.java:10: error: package com.mrousavy.camera.frameprocessor does not exist
